CREATE TABLE IF NOT EXISTS `properties` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  `price` varchar(100) DEFAULT NULL,
  `no_of_beds` int(11) DEFAULT NULL,
  `no_of_bath` int(11) DEFAULT NULL,
  `sq_ft` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `youtube` varchar(255) DEFAULT NULL,
  `floorbeadroom` int(11) DEFAULT NULL,
  `size` varchar(50) DEFAULT NULL,
  `floorImage` longtext DEFAULT NULL,
  `company` longtext DEFAULT NULL,
  `connectivity` longtext DEFAULT NULL,
  `lifestyle` longtext DEFAULT NULL,
  `image` longtext DEFAULT NULL,
  `blueprint` longtext DEFAULT NULL,
  `browsure` longtext DEFAULT NULL,
  `video` longtext DEFAULT NULL,
  `contactname` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `estimatedvalue` varchar(100) DEFAULT NULL,
  `status` varchar(20) DEFAULT 'available',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
